### ISSUE TITLE
Need metadata solution

### ISSUE THREAD

**Issue by benvolioT** [rackerlabs/riss#94]
So that we can create an index or table of contents or similar, it'd be good to have some sort of metadata solution.  Perhaps something like [multi-markdown](https://github.com/fletcher/MultiMarkdown).

**Comment by benvolioT** [comment]
See also: http://blog.martinfenner.org/2013/06/29/metadata-in-scholarly-markdown/

**Comment by mmorga** [comment]
You want, metadata, you get metadata. EVERYONE gets metadata!
